# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: qieam
          POSTGRES_HOST: postgres
          POSTGRES_USER: Cyriel
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    container: maven:3.5.4-jdk-8
    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn -B test --file pom.xml
      env:
        DATABASE_URL_TEST: 'postgres://Cyriel:@postgres:5432/qieam'
    - name: Analyse Sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn verify sonar:sonar -Dskiptest -Dsonar.qualitygate.wait=true -Dsonar.projectKey=integration_continue_tp
